module Engine
  class PredicateRegistry
    class UnknownPredicate < StandardError; end

    PREDICATES = {
      "report_present" => Predicates::ReportPresent,
      "branch_created" => Predicates::BranchCreated,
      "tests_passed" => Predicates::TestsPassed,
      "lint_clean" => Predicates::LintClean,
      "coverage_not_decreased" => Predicates::CoverageNotDecreased,
      "review_verdict" => Predicates::ReviewVerdict,
      "checks_passed" => Predicates::ChecksPassed,
      "security_reviewed" => Predicates::SecurityReviewed,
      "coverage_checked" => Predicates::CoverageChecked,
      "clusters_created" => Predicates::ClustersCreated,
      "configs_collected" => Predicates::ConfigsCollected,
      "assessment_complete" => Predicates::AssessmentComplete,
      "candidates_identified" => Predicates::CandidatesIdentified,
      "removals_verified" => Predicates::RemovalsVerified,
      "removals_drafted" => Predicates::RemovalsDrafted,
      "error_patterns_found" => Predicates::ErrorPatternsFound,
      "severity_classified" => Predicates::SeverityClassified,
      "fixes_drafted" => Predicates::FixesDrafted,
      "scan_completed" => Predicates::ScanCompleted,
      "runbook_mapped" => Predicates::RunbookMapped,
      "runbook_drafted" => Predicates::RunbookDrafted,
      "validation_passed" => Predicates::ValidationPassed,
      "coverage_map_produced" => Predicates::CoverageMapProduced,
      "test_plan_produced" => Predicates::TestPlanProduced,
      "tests_generated" => Predicates::TestsGenerated,
      "flows_mapped" => Predicates::FlowsMapped,
      "boundaries_identified" => Predicates::BoundariesIdentified,
      "endpoint_inventory_produced" => Predicates::EndpointInventoryProduced,
      "docs_diff_produced" => Predicates::DocsDiffProduced,
      "docs_drafted" => Predicates::DocsDrafted,
      "docs_validated" => Predicates::DocsValidated,
      "query_inventory_produced" => Predicates::QueryInventoryProduced,
      "query_analyzed" => Predicates::QueryAnalyzed,
      "query_fixes_drafted" => Predicates::QueryFixesDrafted,
      "log_inventory_produced" => Predicates::LogInventoryProduced,
      "logging_assessed" => Predicates::LoggingAssessed,
      "standard_drafted" => Predicates::StandardDrafted,
      "job_inventory_produced" => Predicates::JobInventoryProduced,
      "observability_assessed" => Predicates::ObservabilityAssessed,
      "disruption_planned" => Predicates::DisruptionPlanned,
      "disruption_executed" => Predicates::DisruptionExecuted,
      "impact_observed" => Predicates::ImpactObserved,
      "recovery_evaluated" => Predicates::RecoveryEvaluated,
      "alerts_detected" => Predicates::AlertsDetected,
      "damage_assessed" => Predicates::DamageAssessed,
      "diagnosis_produced" => Predicates::DiagnosisProduced,
      "diff_produced" => Predicates::DiffProduced,
      "drift_classified" => Predicates::DriftClassified,
      "runbook_selected" => Predicates::RunbookSelected,
      "runbook_executed" => Predicates::RunbookExecuted,
      "recovery_verified" => Predicates::RecoveryVerified,
      "service_inventory_produced" => Predicates::ServiceInventoryProduced,
      "readiness_scored" => Predicates::ReadinessScored,
      "gaps_identified" => Predicates::GapsIdentified,
      "improvements_drafted" => Predicates::ImprovementsDrafted,
      "secrets_scanned" => Predicates::SecretsScanned,
      "dependencies_mapped" => Predicates::DependenciesMapped,
      "risk_assessed" => Predicates::RiskAssessed,
      "rotation_planned" => Predicates::RotationPlanned,
      "artifacts_ingested" => Predicates::ArtifactsIngested,
      "audit_produced" => Predicates::AuditProduced,
      "upgrade_plan_produced" => Predicates::UpgradePlanProduced,
      "upgrade_drafted" => Predicates::UpgradeDrafted,
      "impact_mapped" => Predicates::ImpactMapped,
      "risks_enumerated" => Predicates::RisksEnumerated,
      "repairs_drafted" => Predicates::RepairsDrafted,
      "response_evaluated" => Predicates::ResponseEvaluated,
      "rollback_drafted" => Predicates::RollbackDrafted,
      "rollback_tested" => Predicates::RollbackTested,
      "root_cause_analyzed" => Predicates::RootCauseAnalyzed,
      "rules_defined" => Predicates::RulesDefined,
      "sync_planned" => Predicates::SyncPlanned,
      "timeline_reconstructed" => Predicates::TimelineReconstructed,
      "updates_drafted" => Predicates::UpdatesDrafted,
      "violations_scanned" => Predicates::ViolationsScanned
    }.freeze

    def self.resolve(name)
      PREDICATES.fetch(name) { raise UnknownPredicate, "unknown predicate: #{name}" }
    end
  end
end
