require "rails_helper"

RSpec.describe Engine::PredicateRegistry do
  it "resolves known predicate names" do
    expect(described_class.resolve("tests_passed")).to eq(Engine::Predicates::TestsPassed)
    expect(described_class.resolve("review_verdict")).to eq(Engine::Predicates::ReviewVerdict)
    expect(described_class.resolve("clusters_created")).to eq(Engine::Predicates::ClustersCreated)
    expect(described_class.resolve("assessment_complete")).to eq(Engine::Predicates::AssessmentComplete)
    expect(described_class.resolve("error_patterns_found")).to eq(Engine::Predicates::ErrorPatternsFound)
    expect(described_class.resolve("severity_classified")).to eq(Engine::Predicates::SeverityClassified)
    expect(described_class.resolve("fixes_drafted")).to eq(Engine::Predicates::FixesDrafted)
    expect(described_class.resolve("runbook_mapped")).to eq(Engine::Predicates::RunbookMapped)
    expect(described_class.resolve("runbook_drafted")).to eq(Engine::Predicates::RunbookDrafted)
    expect(described_class.resolve("validation_passed")).to eq(Engine::Predicates::ValidationPassed)
    expect(described_class.resolve("coverage_map_produced")).to eq(Engine::Predicates::CoverageMapProduced)
    expect(described_class.resolve("test_plan_produced")).to eq(Engine::Predicates::TestPlanProduced)
    expect(described_class.resolve("tests_generated")).to eq(Engine::Predicates::TestsGenerated)
    expect(described_class.resolve("endpoint_inventory_produced")).to eq(Engine::Predicates::EndpointInventoryProduced)
    expect(described_class.resolve("docs_diff_produced")).to eq(Engine::Predicates::DocsDiffProduced)
    expect(described_class.resolve("docs_drafted")).to eq(Engine::Predicates::DocsDrafted)
    expect(described_class.resolve("docs_validated")).to eq(Engine::Predicates::DocsValidated)
    expect(described_class.resolve("query_inventory_produced")).to eq(Engine::Predicates::QueryInventoryProduced)
    expect(described_class.resolve("query_analyzed")).to eq(Engine::Predicates::QueryAnalyzed)
    expect(described_class.resolve("query_fixes_drafted")).to eq(Engine::Predicates::QueryFixesDrafted)
    expect(described_class.resolve("log_inventory_produced")).to eq(Engine::Predicates::LogInventoryProduced)
    expect(described_class.resolve("logging_assessed")).to eq(Engine::Predicates::LoggingAssessed)
    expect(described_class.resolve("standard_drafted")).to eq(Engine::Predicates::StandardDrafted)
    expect(described_class.resolve("candidates_identified")).to eq(Engine::Predicates::CandidatesIdentified)
    expect(described_class.resolve("removals_verified")).to eq(Engine::Predicates::RemovalsVerified)
    expect(described_class.resolve("removals_drafted")).to eq(Engine::Predicates::RemovalsDrafted)
    expect(described_class.resolve("job_inventory_produced")).to eq(Engine::Predicates::JobInventoryProduced)
    expect(described_class.resolve("observability_assessed")).to eq(Engine::Predicates::ObservabilityAssessed)
    expect(described_class.resolve("disruption_planned")).to eq(Engine::Predicates::DisruptionPlanned)
    expect(described_class.resolve("disruption_executed")).to eq(Engine::Predicates::DisruptionExecuted)
    expect(described_class.resolve("impact_observed")).to eq(Engine::Predicates::ImpactObserved)
    expect(described_class.resolve("recovery_evaluated")).to eq(Engine::Predicates::RecoveryEvaluated)
    expect(described_class.resolve("alerts_detected")).to eq(Engine::Predicates::AlertsDetected)
    expect(described_class.resolve("diagnosis_produced")).to eq(Engine::Predicates::DiagnosisProduced)
    expect(described_class.resolve("runbook_selected")).to eq(Engine::Predicates::RunbookSelected)
    expect(described_class.resolve("runbook_executed")).to eq(Engine::Predicates::RunbookExecuted)
    expect(described_class.resolve("recovery_verified")).to eq(Engine::Predicates::RecoveryVerified)
    expect(described_class.resolve("service_inventory_produced")).to eq(Engine::Predicates::ServiceInventoryProduced)
    expect(described_class.resolve("readiness_scored")).to eq(Engine::Predicates::ReadinessScored)
    expect(described_class.resolve("gaps_identified")).to eq(Engine::Predicates::GapsIdentified)
    expect(described_class.resolve("improvements_drafted")).to eq(Engine::Predicates::ImprovementsDrafted)
    expect(described_class.resolve("service_inventory_produced")).to eq(Engine::Predicates::ServiceInventoryProduced)
    expect(described_class.resolve("readiness_scored")).to eq(Engine::Predicates::ReadinessScored)
    expect(described_class.resolve("gaps_identified")).to eq(Engine::Predicates::GapsIdentified)
    expect(described_class.resolve("improvements_drafted")).to eq(Engine::Predicates::ImprovementsDrafted)
  end

  it "raises for unknown predicate names" do
    expect { described_class.resolve("teleport_completed") }.to raise_error(Engine::PredicateRegistry::UnknownPredicate)
  end
end
