default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  username: <%= ENV.fetch("POSTGRES_USER", "stupidclaw") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "stupidclaw") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5433) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: stupidclaw_development

test:
  <<: *default
  database: stupidclaw_test

production:
  primary: &primary_production
    <<: *default
    database: stupidclaw_production
    username: stupidclaw
    password: <%= ENV["STUPIDCLAW_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: stupidclaw_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: stupidclaw_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: stupidclaw_production_cable
    migrations_paths: db/cable_migrate
